FROM azul/zulu-openjdk-alpine:21-latest AS build
ENV DOCKER_PIPELINE=true
WORKDIR /output
COPY . ./
RUN ./gradlew kumaslash-anilist:bootJar

FROM azul/zulu-openjdk-alpine:21-jre-headless-latest AS kumaslash
WORKDIR /deploy
COPY --from=build /output/kumaslash-anilist/build/libs/*.jar kumaslash.jar
CMD ["java", "-jar", "kumaslash.jar"]
