# This YAML file is for spring-boot-docker-compose
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DBS: guild,tachiyomi
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker_pg_init:/docker-entrypoint-initdb.d
    labels:
      org.springframework.boot.service-connection: postgres
  adminer:
    image: adminer
    ports:
      - 8888:8080
