---
spring:
  main:
    web-application-type: "none"
  datasource:
    url: "jdbc:postgresql://localhost:5432/mydatabase"
    username: "myuser"
    password: "secret"
  sql:
    init:
      mode: "always"
  profiles:
    include: "sentry"
