on:
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:
jobs:
  validate-wrapper:
    runs-on: ubuntu-latest
    name: Validate Gradle Wrapper
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
  build:
    runs-on: ubuntu-latest
    name: Build Java Application
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup Java 20
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '20'
          cache: 'gradle'
      - name: Build With Gradle
        run: ./gradlew build --no-daemon
