on:
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:
jobs:
  validate-wrapper:
    runs-on: ubuntu-latest
    name: Validate Gradle Wrapper
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '20', '21-ea' ]
    name: Build Application with Java ${{ matrix.Java }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup Java ${{ matrix.Java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.Java }}
          cache: 'gradle'
      - name: Build With Gradle
        run: ./gradlew build --no-daemon
